### ISSUE TITLE
поломались ссылки на вакансии 

### ISSUE THREAD

**Issue by dpolyakov** [dodopizza/dodopizzadev#4]
У вас в 41e8b1ada7c3f50eb38b76bf7fb5003483bfeae0 поломались ссылки на вакансии. 
В файле маркдаун, а шаблонизатор в такое, похоже, не умеет, поэтому ссылки `https://dodo.dev/[https://dodobrands.huntflow.io/vacancy/fullstack-developer-1](https://dodobrands.huntflow.io/vacancy/fullstack-developer-1)`

**Comment by selfdeceited** [comment]
Я сам мимо проходил и только что обнаружил случайно, пофиксил

**Comment by selfdeceited** [comment]
спасибо за фидбек! сорри, что столько времени не отвечали :(

**Comment by selfdeceited** [comment]
@nikolay-chugunov-dodopizza FYI

**Comment by nikolay-chugunov-dodopizza** [comment]
@selfdeceited, @dpolyakov  Спасибо за инфо! Приму к сведению.
